# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonFixer
                                 A QGIS plugin
 This plugin detect and fix overlapping,  self interesection, line intersetion and close gaps from adjacant geometries
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-03
        copyright            : (C) 2020 by M. Andaç Derinpınar
        email                : mustafaderinpinar@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolygonFixer class from file PolygonFixer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygonfixer import PolygonFixer
    return PolygonFixer(iface)
